# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /funds-confirmations_post for http method type POST 
# RoostTestHash=d3d3a7c8c5
# 
# 

# ********RoostGPT********
Feature: Create Funds Confirmation

Background:
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']

Scenario Outline: Testing Create Funds Confirmation API
    Given path '/funds-confirmations'
    And headers  { 
                    'Authorization': '#(AUTH_TOKEN)', 
                    'x-fapi-auth-date': '<x-fapi-auth-date>', 
                    'x-fapi-customer-ip-address': '<x-fapi-customer-ip-address>', 
                    'x-fapi-interaction-id': '<x-fapi-interaction-id>', 
                    'x-customer-user-agent': '<x-customer-user-agent>'
                  }
    And request
    """
    {
        "Data": {
        "ConsentId": "<ConsentId>",
        "Reference": "<Reference>",
        "InstructedAmount": {
            "Amount": "<Amount>",
            "Currency": "<Currency>"
        }
        }
    }
    """
    When method post
    Then status 201
    And match responseHeaders contains { 'x-fapi-interaction-id': '#string'}
    And match response ==
    """
    {
        "Data": {
        "FundsConfirmationId": "#string",
        "ConsentId": "<ConsentId>",
        "CreationDateTime": "#string",
        "FundsAvailable": "#boolean",
        "Reference": "<Reference>",
        "InstructedAmount": {
            "Amount": "<Amount>",
            "Currency": "<Currency>"
        }
        },
        "Links": {
        "Self": "#string"
        }
    }
    """

Examples:
    | x-fapi-auth-date            | x-fapi-customer-ip-address | x-fapi-interaction-id                | x-customer-user-agent  | ConsentId  | Reference | Amount | Currency |
    | Wed, 30 Nov 2022 15:05:25 GMT  | 12.201.45.125              | f8273b70-d5c0-4ef7-b3ba-2b3400fe1956 | Mozilla/5.0 (Macintosh, etc.)    | 2537482945 | 12345     | 0.01   | GBP       |
