# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /funds-confirmation-consents_post for http method type POST 
# RoostTestHash=db407f0790
# 
# 

# ********RoostGPT********
Feature: Create Funds Confirmation Consent

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* def auth_token = karate.properties['AUTH_TOKEN']
* header Authorization = 'Bearer ' + auth_token

Scenario Outline: Successful creation of funds confirmation consent
Given path '/funds-confirmation-consents'
And request { "Data": { "ExpirationDateTime": "<expirationDateTime>", "DebtorAccount": { "SchemeName": "<schemeName>", "Identification": "<identification>", "Name": "<accountName>", "SecondaryIdentification": "<secondaryIdentification>" } } }
When method post
Then status 201
And match response.Data.ConsentId == "#string"
And match response.Data.Status == "AwaitingAuthorisation"

Examples:
| expirationDateTime         | schemeName    | identification | accountName | secondaryIdentification |
| '2023-10-05T10:53:10+00:00' | 'UK.OBIE.IBAN' | '40010600962147' | 'ABC'   | 'Roll 56922'     |

Scenario: Error in creating funds confirmation consent with missing required fields
Given path '/funds-confirmation-consents'
And request {}
When method post
Then status 400
And match response.Code == 'ERR-4231'
And match response.Id == '#string'
And match response.Message == 'There is something wrong with the request parameters provided'

Scenario: Error in creating funds confirmation consent with invalid auth token
Given path '/funds-confirmation-consents'
And request { "Data": { "ExpirationDateTime": "2023-10-05T10:53:10+00:00", "DebtorAccount": { "SchemeName": "UK.OBIE.IBAN", "Identification": '40010600962147', "Name": "ABC", "SecondaryIdentification": "Roll 56922" } } }
And header Authorization = 'Bearer invalid'
When method post
Then status 401
