# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /funds-confirmations_post for http method type POST 
# RoostTestHash=d3d3a7c8c5
# 
# 

# ********RoostGPT********
---ROOST FEATURES START--- 
 Feature: Funds Confirmation API Test

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def headerParam = { 'x-fapi-auth-date': 'Wed, 30 Nov 2022 15:05:25 UTC', 'x-fapi-customer-ip-address': '12.201.45.125', 'x-fapi-interaction-id': 'f8273b70-d5c0-4ef7-b3ba-2b3400fe1956', 'Authorization': '#('Bearer ' + AUTH_TOKEN)', 'x-customer-user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' }

  Scenario Outline: Verify funds confirmation creation
    Given path '/funds-confirmations'
    And request { "Data": { "ConsentId": "<consentId>", "Reference": "<reference>", "InstructedAmount": { "Amount": "<amount>", "Currency": "<currency>" } } }
    And headers headerParam
    When method post
    Then status 201
    And match response == """{ "Data": { "FundsConfirmationId": "#notnull", "ConsentId": "<consentId>", "CreationDateTime": "#notnull", "FundsAvailable": true, "Reference": "<reference>", "InstructedAmount": { "Amount": "<amount>", "Currency": "<currency>" } }, "Links": { "Self": "#notnull" } }"""

  Examples:
    | consentId  | reference  | amount  |  currency |
    | '2537482945'  | '12345'  | '0.01'  |'GBP'  |
 
---ROOST FEATURES END---
