# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /funds-confirmation-consents/{ConsentId}_delete for http method type DELETE 
# RoostTestHash=5267390b19
# 
# 

# ********RoostGPT********
Feature: Funds Confirmation Consent API

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* def auth_token = karate.properties['AUTH_TOKEN']
* def request_headers = 
"""
{
  "Authorization": "#(auth_token)",
  "x-fapi-auth-date": "Wed, 30 Nov 2022 15:05:25 UTC",
  "x-fapi-customer-ip-address": "12.201.45.125",
  "x-fapi-interaction-id": "f8273b70-d5c0-4ef7-b3ba-2b3400fe1956",
  "x-customer-user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
}
"""

Scenario Outline: Delete Funds Confirmation Consent
  Given path '/funds-confirmation-consents/', '<ConsentId>'
  And headers request_headers
  When method delete
  Then match status 204 
  And match responseHeaders contains {"x-fapi-interaction-id":"#string"}

Examples:
| ConsentId  |
| '764331140'|
| '987654321'|
| '123456789'|

Scenario Outline: Verify Error Response
  Given path '/funds-confirmation-consents/', '<ConsentId>'
  And headers request_headers
  When method delete
  Then match status 400
  And match response.Code == 'ERR-4231'
  And match response.Id == "#string"
  And match response.Message == "There is something wrong with the request parameters provided"
  And match response.Errors[0].ErrorCode == 'UK.OBIE.Field.InvalidDate'
  
Examples:
| ConsentId |
| 'invalid' |
| ' '       |
