# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /funds-confirmation-consents/{ConsentId}_delete for http method type DELETE 
# RoostTestHash=5267390b19
# 
# 

# ********RoostGPT********
Feature: Delete Funds Confirmation Consent

  Background: 
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * def authToken = karate.properties['AUTH_TOKEN']
    * url urlBase

  Scenario Outline: Delete funds confirmation consent with valid ConsentId and request headers
    Given path '/funds-confirmation-consents/', '<ConsentId>'
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Authorization = 'Bearer ' + authToken
    And header x-customer-user-agent = '<x-customer-user-agent>'
    When method delete
    Then status 204
    And match responseHeaders['x-fapi-interaction-id'] == '<x-fapi-interaction-id>'
    Examples:
      | ConsentId    | x-fapi-auth-date       | x-fapi-customer-ip-address | x-fapi-interaction-id                  | x-customer-user-agent                                                                    |
      | '764331140'   | 'Wed, 30 Nov 2022 15:05:25 UTC' | '12.201.45.125'           | 'f8273b70-d5c0-4ef7-b3ba-2b3400fe1956' | 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' |

