# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Laureate API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080') 
  * url urlBase

Scenario Outline: Obtain information about a specific Nobel Prize Laureate
  Given path '/2.1/laureate', '<laureateID>'
  When method get
  Then status 200
  And match response.laureate.id == '<laureateID>'
  And match response.laureate == '#object'

Examples:
  | laureateID |
  | 1          |
  | 2          |
  | 3          |

Scenario Outline: Test for incorrect laureateID in the endpoint
  Given path '/2.1/laureate', '<laureateID>'
  When method get
  Then status 404

Examples:
  | laureateID |
  | 99999      |
  | abc        |
  | ''         |
