# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Information

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = authToken

Scenario Outline: Get Nobel Prize information by category and year

    Given path '2.1', 'nobelPrize', '<category>', '<year>'
    When method get
    Then status <expectedStatus>
    And match response contains { nobelPrize: '#object' }

    Examples:
    | category | year | expectedStatus |
    | 'phy'    | 2001 | 200           |
    | 'phy'    | 1800 | 422           |
    | 'med'    | 2001 | 200           |
    | 'med'    | 1800 | 422           |
    | 'che'    | 2001 | 200           |
    | 'che'    | 1800 | 422           |
    | 'lit'    | 2001 | 200           |
    | 'lit'    | 1800 | 422           |
    | 'pea'    | 2001 | 200           |
    | 'pea'    | 1800 | 422           |
    | 'eco'    | 2001 | 200           |
    | 'eco'    | 1800 | 422           |

Scenario: Invalid category

    Given path '2.1', 'nobelPrize', 'abc', '2001'
    When method get
    Then status 400

Scenario: Invalid year

    Given path '2.1', 'nobelPrize', 'phy', 'abc'
    When method get
    Then status 400

Scenario: Missing category

    Given path '2.1', 'nobelPrize', , '2001'
    When method get
    Then status 404

Scenario: Missing year

    Given path '2.1', 'nobelPrize', 'phy', 
    When method get
    Then status 404
