# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Information Feature

Background: 
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase

Scenario Outline: Get Nobel Prize Information by Category and Year
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method get
    Then status 200
    And match response == {nobelPrize: '#object'}
    And match response.nobelPrize contains { awardYear:'#integer', category:'#object', categoryFullName:'#object', dateAwarded:'#string', prizeAmount:'#integer', prizeAmountAdjusted:'#integer', topMotivation:'#object', laureates:'#array'}
  
Examples:
| category | year |
| 'Physics'  | 2012 |
| 'Chemistry' | 1997 |
| 'Medicine'  | 2018 |

Scenario Outline: Nobel Prize Information - Malformed Request
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method get
    Then status 400
  
Examples:
| category | year |
| 'Physics123'  | 2012 |
| 'Chemistry' | 199abc7 |
| 'Medicine'  | 'abc' |

Scenario Outline: Nobel Prize Information - Non-existent Resource
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method get
    Then status 404
  
Examples:
| category | year |
| 'IntlPeace'  | 1800 |
| 'Physics' | 2050 |

Scenario Outline: Nobel Prize Information - Semantically Incorrect Request
    Given path '2.1/nobelPrize', '<category>', '<year>'
    When method get
    Then status 422
  
Examples:
| category | year |
| 'Chemistry'  | -1 |
| '' | 1997 |
