# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API

Background:

* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')  

* url urlBase
  
* def authToken = karate.properties['AUTH_TOKEN']

* header Authorization = authToken


Scenario: Ability to fetch nobel prizes data successfully

    Given path '/2.1/nobelPrizes'
    And param offset = 1
    And param limit = 10
    And param sort = 'year'
    And param nobelPrizeYear = 2020
    And param yearTo = 2023
    And param nobelPrizeCategory = 'eco'
    And param format = 'json'
    And param csvLang = 'en'
    
    When method get

    Then status 200
    And match response == { nobelPrizes: '#[]', meta: '#object', links: '#array' }

    And match each response.nobelPrizes[*].awardYear == '#integer'
    And match each response.nobelPrizes[*].prizeAmount == '#integer'
    And match each response.nobelPrizes[*].prizeAmountAdjusted == '#integer'

    And match response.meta.offset == 1
    And match response.meta.limit == 10
    And match response.meta.nobelPrizeYear == 2020
    And match response.meta.yearTo == 2023
    And match response.meta.nobelPrizeCategory == 'eco'


Scenario: Attempt to fetch nobel prize data with a non-existent prize year  

    Given path '/2.1/nobelPrizes'
    And param nobelPrizeYear = 1234 

    When method get

    Then status 400
    And match response.code == '400'
    And match response.message == 'There is not Laureate born that date'


Scenario: Attempt to fetch nobel prize data with a malformed syntax

    Given path '/2.1/nobelPrizes'
    And param limit = 'abcd' 

    When method get

    Then status 400
    And match response.code == '400'
    And match response.message == '#string'
