# ********RoostGPT********

# Test generated by RoostGPT for test claude-karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=81e2a40d4b
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Laureate API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario: Get laureate information by ID
  * def laureateID = 456
  Given path '/2.1/laureate/', laureateID
  When method GET
  Then status 200
  And match response == 
  """
  {
    "laureate": {
      "id": "#number",
      "laureateIfPerson": {
        "knownName": {
          "en": "#string",
          "se": "#string",
          "no": "#string"  
        },
        "givenName": {
          "en": "#string",
          "se": "#string", 
          "no": "#string"
        },
        "familyName": {
          "en": "#string",
          "se": "#string",
          "no": "#string"  
        },
        "fullName": {
          "en": "#string",
          "se": "#string",
          "no": "#string"
        },
        "filename": "#string",
        "penname": "##string",
        "gender": "#string",
        "birth": {
          "date": "#ignore",
          "place": {
            "city": {
              "en": "#string",
              "se": "#string",
              "no": "#string"
            },
            "country": {
              "en": "#string", 
              "se": "#string",
              "no": "#string"
            },
            "cityNow": {
              "en": "#string",
              "se": "#string", 
              "no": "#string",
              "sameAs": "#array"
            },
            "countryNow": {
              "en": "#string",
              "se": "#string",
              "no": "#string", 
              "sameAs": "#array"
            },
            "continent": {
              "en": "#string",
              "se": "#string",
              "no": "#string"
            },
            "locationString": {
              "en": "#string",
              "se": "#string",
              "no": "#string"
            }
          }
        },
        "death": "##object"
      },
      "laureateIfOrg": "##object",
      "wikipedia": {
        "slug": "#string",
        "english": "#string"
      },
      "wikidata": {
        "id": "#string",
        "url": "#string"  
      },
      "sameAs": "#array",
      "links": "#array",
      "nobelPrizes": "#array"
    }
  }
  """
  And match response.laureate.id == laureateID
  And match response.laureate.laureateIfPerson.gender == '#string'
  And match response.laureate.wikipedia.slug == '#string'
  And match each response.laureate.nobelPrizes[*].awardYear == '#number'
  And match each response.laureate.nobelPrizes[*].category.en == '#string'
  And match each response.laureate.nobelPrizes[*].affiliations[*].name.en == '#string'

Scenario: Get laureate with invalid ID
  Given path '/2.1/laureate/0'
  When method GET
  Then status 400
  And match response == 
  """
  {
    "code": "#string",
    "message": "#string"
  }
  """

Scenario: Get laureate with non-existent ID
  Given path '/2.1/laureate/999999'
  When method GET
  Then status 404
  And match response ==
  """
  {
    "code": "#string",
    "message": "#string" 
  }
  """
