# ********RoostGPT********

# Test generated by RoostGPT for test claude-karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=8f84ba8c38
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
  * url target
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario: Get all Nobel Prizes
  Given path '/2.1/nobelPrizes'
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match response.nobelPrizes == '#array'
  And match each response.nobelPrizes contains { awardYear: '#number', category: '#object', categoryFullName: '#object', dateAwarded: '#string', prizeAmount: '#number', prizeAmountAdjusted: '#number', topMotivation: '#object', laureates: '#array' }
  And match response.meta == '#object'
  And match response.links == '#array'

Scenario: Get Nobel Prizes with pagination
  Given path '/2.1/nobelPrizes'
  And param offset = 1
  And param limit = 10  
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match response.nobelPrizes == '#[10]'
  And match response.meta.offset == 1
  And match response.meta.limit == 10
  And match response.links contains {rel: 'next'}

Scenario: Get Nobel Prizes by year
  Given path '/2.1/nobelPrizes'
  And param nobelPrizeYear = 2020
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json' 
  And match each response.nobelPrizes contains {awardYear: 2020}
  And match response.meta.nobelPrizeYear == 2020

Scenario: Get Nobel Prizes by year range
  Given path '/2.1/nobelPrizes'
  And param nobelPrizeYear = 2015
  And param yearTo = 2020
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match each response.nobelPrizes contains {awardYear: '#? _ >= 2015 && _ <= 2020'}
  And match response.meta.nobelPrizeYear == 2015
  And match response.meta.yearTo == 2020

Scenario: Get Nobel Prizes by category
  Given path '/2.1/nobelPrizes'  
  And param nobelPrizeCategory = 'phy'
  When method GET
  Then status 200 
  And match header Content-Type contains 'application/json'
  And match each response.nobelPrizes contains {category: {en: 'Physics'}}
  And match response.meta.nobelPrizeCategory == 'phy'

Scenario: Get Nobel Prizes in CSV format
  Given path '/2.1/nobelPrizes'
  And param format = 'csv'
  When method GET
  Then status 200
  And match header Content-Type contains 'text/csv'

Scenario: Get Nobel Prizes in CSV format with language
  Given path '/2.1/nobelPrizes'
  And param format = 'csv'  
  And param csvLang = 'se'
  When method GET
  Then status 200
  And match header Content-Type contains 'text/csv'
  # Add more language specific checks

Scenario: Get Nobel Prizes with invalid year
  Given path '/2.1/nobelPrizes'
  And param nobelPrizeYear = 1800
  When method GET
  Then status 400
  And match response == {code: '#string', message: '#string'}

Scenario: Get Nobel Prizes with invalid category  
  Given path '/2.1/nobelPrizes'
  And param nobelPrizeCategory = 'invalid'
  When method GET
  Then status 422
  And match response == {code: '#string', message: '#string'}
