# ********RoostGPT********

# Test generated by RoostGPT for test claude-karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=00eb351b13
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
  * url target
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Get Nobel Prize by category and year
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match response.nobelPrize.awardYear == <year>
  And match response.nobelPrize.category.en == '<categoryEn>'
  And match response.nobelPrize.categoryFullName.en == '<categoryFullEn>'
  And match response.nobelPrize.dateAwarded == '#string'
  And match response.nobelPrize.prizeAmount == '#number'
  And match response.nobelPrize.prizeAmountAdjusted == '#number'
  And match response.nobelPrize.laureates == '#array'
  And match each response.nobelPrize.laureates contains { id: '#number', name: '#object', portion: '#string', sortOrder: '#string', motivation: '#object' }

  Examples:
    | category | year | categoryEn | categoryFullEn |
    | che      | 2020 | Chemistry  | Nobel Prize in Chemistry |
    | eco      | 2019 | Economic Sciences | Nobel Memorial Prize in Economic Sciences |  
    | lit      | 2018 | Literature | Nobel Prize in Literature |
    | pea      | 2017 | Peace      | Nobel Peace Prize |
    | phy      | 2016 | Physics    | Nobel Prize in Physics |
    | med      | 2015 | Physiology or Medicine | Nobel Prize in Physiology or Medicine |

Scenario Outline: Get Nobel Prize with invalid category
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken  
  When method GET
  Then status 400
  And match header Content-Type contains 'application/json'
  And match response == { code: '#string', message: '#string' }
  
  Examples:
    | category | year |
    | invalid  | 2020 |
    | test     | 2019 |

Scenario Outline: Get Nobel Prize with invalid year  
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken
  When method GET
  Then status 404
  And match header Content-Type contains 'application/json'
  And match response == { code: '#string', message: '#string' }

  Examples:
    | category | year |  
    | che      | 1800 |
    | eco      | 2100 |

Scenario Outline: Get Nobel Prize with missing authorization
  Given path '/2.1/nobelPrize/<category>/<year>'
  When method GET
  Then status 401
  And match header Content-Type contains 'application/json'
  And match response == { code: '#string', message: '#string' }

  Examples:
    | category | year |
    | lit      | 2018 | 
    | pea      | 2017 |
