# ********RoostGPT********

# Test generated by RoostGPT for test py-api-aviation using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test file generated for /api/data/airsigmet_get for http method type GET 
# RoostTestHash=790b28c569
# 
# 

# ********RoostGPT********
import pytest
import json
import os
from validator import SwaggerSchemaValidator

# Initialize SwaggerSchemaValidator
validator = SwaggerSchemaValidator('https://aviationweather.gov/data/schema/openapi.yaml')

# Load test data
with open(os.path.join(os.path.dirname(__file__), 'api_data_airsigmet.json'), 'r') as f:
    test_data = json.load(f)

@pytest.mark.parametrize("test_case", test_data)
def test_airsigmet_endpoint(api_client, test_case):
    # Prepare request parameters
    params = {
        'format': test_case['format'],
        'types': ','.join(test_case['types']),
        'hazard': ','.join(test_case['hazard']),
        'level': test_case['level'][0] if isinstance(test_case['level'], list) else test_case['level']
    }

    # Validate request parameters
    try:
        validator.validate_with_schema(params, {
            'type': 'object',
            'properties': {
                'format': {'type': 'string', 'enum': ['raw', 'json', 'geojson', 'xml', 'iwxxm']},
                'types': {'type': 'string'},
                'hazard': {'type': 'string', 'enum': ['conv', 'turb', 'ice', 'ifr']},
                'level': {'type': 'number'}
            }
        })
    except Exception as e:
        if test_case['statusCode'] == 400:
            pytest.xfail(f"Expected validation error: {str(e)}")
        else:
            raise

    # Make API request
    response = api_client.get('/api/data/airsigmet', params=params)

    # Check status code
    assert response.status_code == test_case['statusCode']

    # Validate response for successful operations
    if test_case['statusCode'] == 200:
        content_type = response.headers.get('Content-Type', '')
        
        if 'json' in content_type:
            json_response = response.json()
            validator.validate_json(json_response, 'AirSigmet')
        elif 'xml' in content_type:
            # XML validation would go here
            pass
        elif 'geo+json' in content_type:
            geojson_response = response.json()
            validator.validate_with_schema(geojson_response, {
                'type': 'object',
                'properties': {
                    'type': {'type': 'string', 'enum': ['FeatureCollection']},
                    'features': {
                        'type': 'array',
                        'items': {
                            'type': 'object',
                            'properties': {
                                'type': {'type': 'string', 'enum': ['Feature']},
                                'id': {'type': 'number'},
                                'properties': {'type': 'object'},
                                'geometry': {
                                    'type': 'object',
                                    'properties': {
                                        'type': {'type': 'string', 'enum': ['Polygon']},
                                        'coordinates': {'type': 'array'}
                                    }
                                }
                            }
                        }
                    }
                }
            })
    elif test_case['statusCode'] == 400:
        error_response = response.json()
        validator.validate_with_schema(error_response, {
            'type': 'object',
            'properties': {
                'status': {'type': 'string', 'enum': ['error']},
                'error': {'type': 'string'}
            }
        })

def test_invalid_format(api_client):
    response = api_client.get('/api/data/airsigmet', params={'format': 'invalid'})
    assert response.status_code == 400
    error_response = response.json()
    validator.validate_with_schema(error_response, {
        'type': 'object',
        'properties': {
            'status': {'type': 'string', 'enum': ['error']},
            'error': {'type': 'string'}
        }
    })

def test_invalid_hazard(api_client):
    response = api_client.get('/api/data/airsigmet', params={'hazard': 'invalid'})
    assert response.status_code == 400
    error_response = response.json()
    validator.validate_with_schema(error_response, {
        'type': 'object',
        'properties': {
            'status': {'type': 'string', 'enum': ['error']},
            'error': {'type': 'string'}
        }
    })

def test_invalid_level(api_client):
    response = api_client.get('/api/data/airsigmet', params={'level': 'invalid'})
    assert response.status_code == 400
    error_response = response.json()
    validator.validate_with_schema(error_response, {
        'type': 'object',
        'properties': {
            'status': {'type': 'string', 'enum': ['error']},
            'error': {'type': 'string'}
        }
    })

def test_missing_required_params(api_client):
    response = api_client.get('/api/data/airsigmet')
    assert response.status_code == 200  # All parameters are optional

def test_boundary_level(api_client):
    response = api_client.get('/api/data/airsigmet', params={'level': 999999})
    assert response.status_code == 200  # Assuming no upper limit on level

def test_multiple_hazards(api_client):
    response = api_client.get('/api/data/airsigmet', params={'hazard': 'conv,turb'})
    assert response.status_code == 200
    if 'json' in response.headers.get('Content-Type', ''):
        json_response = response.json()
        validator.validate_json(json_response, 'AirSigmet')

# Instructions for running the tests:
# 1. Ensure you have pytest installed: pip install pytest
# 2. Place this file in the same directory as conftest.py and config.yml
# 3. Run the tests using the command: pytest test_airsigmet.py
