# ********RoostGPT********

# Test generated by RoostGPT for test py-api-aviation using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test file generated for /api/data/isigmet_get for http method type GET 
# RoostTestHash=30b070a852
# 
# 

# ********RoostGPT********
import pytest
import json
import os
from validator import SwaggerSchemaValidator

# Initialize the SwaggerSchemaValidator
validator = SwaggerSchemaValidator("https://aviationweather.gov/data/schema/openapi.yaml")

# Load test data
with open(os.path.join(os.path.dirname(__file__), 'api_data_isigmet.json'), 'r') as f:
    test_data = json.load(f)

@pytest.mark.parametrize("test_case", test_data)
def test_isigmet_endpoint(api_client, test_case):
    """
    Test the /api/data/isigmet endpoint with various scenarios.
    """
    endpoint = "/api/data/isigmet"
    params = {
        "format": test_case["format"],
        "hazard": test_case["hazard"],
        "level": test_case["level"],
        "date": test_case["date"]
    }

    # Validate request parameters
    try:
        validator.validate_with_schema(params, {
            "type": "object",
            "properties": {
                "format": {"type": "string", "enum": ["raw", "json", "geojson", "xml", "iwxxm"]},
                "hazard": {"type": "string", "enum": ["turb", "ice"]},
                "level": {"type": "string"},
                "date": {"type": "string"}
            }
        })
    except Exception as e:
        pytest.fail(f"Request validation failed: {str(e)}")

    # Make the API request
    response = api_client.get(endpoint, params=params)

    # Assert the status code
    assert response.status_code == test_case["statusCode"], f"Expected status code {test_case['statusCode']}, but got {response.status_code}"

    # Validate the response
    if response.status_code == 200:
        content_type = response.headers.get('Content-Type', '')
        if 'application/json' in content_type:
            try:
                validator.validate_json(response.json(), 'ISigmet')
            except Exception as e:
                pytest.fail(f"Response validation failed: {str(e)}")
        elif 'application/geo+json' in content_type:
            try:
                validator.validate_json(response.json(), 'GeoJSONFeatureCollection')
            except Exception as e:
                pytest.fail(f"Response validation failed: {str(e)}")
        # Add more content type validations as needed
    elif response.status_code == 400:
        try:
            validator.validate_json(response.json(), 'ErrorResponse')
        except Exception as e:
            pytest.fail(f"Error response validation failed: {str(e)}")

    # Additional assertions based on the scenario
    if test_case["scenario"] == "Successful operation":
        assert response.text, "Response body should not be empty for successful operation"
    elif test_case["scenario"] == "Input validation errors":
        error_response = response.json()
        assert "error" in error_response, "Error response should contain an 'error' field"

def test_isigmet_invalid_params(api_client):
    """
    Test the /api/data/isigmet endpoint with invalid parameters.
    """
    endpoint = "/api/data/isigmet"
    params = {
        "format": "invalid",
        "hazard": "invalid",
        "level": "invalid",
        "date": "invalid"
    }

    response = api_client.get(endpoint, params=params)
    assert response.status_code == 400, "Expected 400 Bad Request for invalid parameters"

    try:
        validator.validate_json(response.json(), 'ErrorResponse')
    except Exception as e:
        pytest.fail(f"Error response validation failed: {str(e)}")

def test_isigmet_missing_params(api_client):
    """
    Test the /api/data/isigmet endpoint with missing parameters.
    """
    endpoint = "/api/data/isigmet"
    response = api_client.get(endpoint)
    
    # Since all parameters are optional, this should still return a 200 OK
    assert response.status_code == 200, "Expected 200 OK for request with no parameters"

    content_type = response.headers.get('Content-Type', '')
    if 'application/json' in content_type:
        try:
            validator.validate_json(response.json(), 'ISigmet')
        except Exception as e:
            pytest.fail(f"Response validation failed: {str(e)}")

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
