# ********RoostGPT********

# Test generated by RoostGPT for test py-api-aviation using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test file generated for /api/data/taf_get for http method type GET 
# RoostTestHash=839f54b60c
# 
# 

# ********RoostGPT********
import pytest
import json
import os
from validator import SwaggerSchemaValidator

# Initialize SwaggerSchemaValidator
validator = SwaggerSchemaValidator("https://aviationweather.gov/data/schema/openapi.yaml")

# Load test data from JSON file
with open('api_data_taf.json', 'r') as f:
    test_data = json.load(f)

@pytest.mark.parametrize("test_case", test_data)
def test_taf_endpoint(api_client, config, test_case):
    # Prepare request parameters
    params = {
        "ids": test_case["ids"],
        "bbox": test_case["bbox"],
        "format": test_case["format"],
        "metar": test_case["metar"],
        "time": test_case["time"],
        "date": test_case["date"]
    }

    # Validate request parameters
    request_schema = {
        "type": "object",
        "properties": {
            "ids": {"type": "string"},
            "bbox": {"type": "string"},
            "format": {"type": "string", "enum": ["raw", "json", "geojson", "xml", "iwxxm"]},
            "metar": {"type": "boolean"},
            "time": {"type": "string", "enum": ["valid", "issue"]},
            "date": {"type": "string"}
        }
    }
    validator.validate_with_schema(params, request_schema)

    # Make API request
    response = api_client.get("/api/data/taf", params=params)

    # Assert status code
    assert response.status_code == test_case["statusCode"], f"Expected status code {test_case['statusCode']}, but got {response.status_code}"

    # Validate response
    if response.status_code == 200:
        if params["format"] == "json":
            validator.validate_json(response.json(), "TAF")
        elif params["format"] == "geojson":
            validator.validate_json(response.json(), "GeoJSON")
        elif params["format"] in ["xml", "iwxxm"]:
            # XML validation would require additional XML schema validation logic
            pass
        else:
            # For raw format, we can't validate the structure
            assert isinstance(response.text, str)
    elif response.status_code == 400:
        error_schema = {
            "type": "object",
            "properties": {
                "status": {"type": "string", "enum": ["error"]},
                "error": {"type": "string"}
            },
            "required": ["status", "error"]
        }
        validator.validate_with_schema(response.json(), error_schema)

    # Additional assertions based on the scenario
    if test_case["scenario"] == "successful operation":
        assert response.status_code == 200, "Expected successful operation"
    elif test_case["scenario"] == "Input validation errors":
        assert response.status_code == 400, "Expected input validation error"
        error_response = response.json()
        assert "error" in error_response, "Error message should be present in the response"

def test_taf_endpoint_missing_required_params(api_client):
    # Test with missing required parameters
    response = api_client.get("/api/data/taf")
    assert response.status_code == 400, "Expected 400 status code for missing required parameters"

def test_taf_endpoint_invalid_format(api_client):
    # Test with invalid format
    params = {"format": "invalid_format"}
    response = api_client.get("/api/data/taf", params=params)
    assert response.status_code == 400, "Expected 400 status code for invalid format"

def test_taf_endpoint_invalid_date(api_client):
    # Test with invalid date
    params = {"date": "invalid_date"}
    response = api_client.get("/api/data/taf", params=params)
    assert response.status_code == 400, "Expected 400 status code for invalid date"

if __name__ == "__main__":
    pytest.main([__file__, "-v"])
