# ********RoostGPT********

# Test generated by RoostGPT for test py-api-aviation using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test file generated for /api/data/metar_get for http method type GET 
# RoostTestHash=23d1bed220
# 
# 

# ********RoostGPT********
import pytest
import json
import os
from validator import SwaggerSchemaValidator

# Initialize SwaggerSchemaValidator
validator = SwaggerSchemaValidator("https://aviationweather.gov/data/schema/openapi.yaml")

# Load test data
with open(os.path.join(os.path.dirname(__file__), 'api_data_metar.json'), 'r') as f:
    test_data = json.load(f)

@pytest.mark.parametrize("test_case", test_data)
def test_metar_api(api_client, config, test_case):
    """
    Test the METAR API endpoint with various scenarios.
    """
    endpoint = "/api/data/metar"
    
    # Prepare request parameters
    params = {
        "ids": ",".join(test_case["ids"]),
        "bbox": ",".join(map(str, test_case["bbox"])),
        "format": test_case["format"],
        "taf": test_case["taf"],
        "hours": test_case["hours"],
        "date": test_case["date"]
    }
    
    # Validate request parameters
    try:
        validator.validate_with_schema(params, {
            "type": "object",
            "properties": {
                "ids": {"type": "string"},
                "bbox": {"type": "string"},
                "format": {"type": "string"},
                "taf": {"type": ["boolean", "string"]},
                "hours": {"type": ["number", "string"]},
                "date": {"type": "string"}
            }
        })
    except Exception as e:
        pytest.fail(f"Request validation failed: {str(e)}")

    # Make API request
    response = api_client.get(endpoint, params=params)

    # Check status code
    assert response.status_code == test_case["statusCode"], f"Expected status code {test_case['statusCode']}, but got {response.status_code}"

    # Validate response
    if response.status_code == 200:
        try:
            if test_case["format"] == "json":
                validator.validate_json(response.json(), "METAR")
            elif test_case["format"] == "geojson":
                validator.validate_json(response.json(), "GeoJSON")
            elif test_case["format"] == "xml":
                # XML validation is not implemented in the given validator
                pass
            else:
                # For raw, decoded, iwxxm formats, we can't validate the schema
                pass
        except Exception as e:
            pytest.fail(f"Response validation failed: {str(e)}")
    elif response.status_code == 400:
        try:
            validator.validate_json(response.json(), "Error")
        except Exception as e:
            pytest.fail(f"Error response validation failed: {str(e)}")

    # Additional assertions based on the scenario
    if test_case["scenario"] == "successful operation":
        assert response.text, "Response body should not be empty for successful operation"
    elif test_case["scenario"] == "Input validation errors":
        assert "error" in response.json(), "Error message should be present in the response for input validation errors"

if __name__ == "__main__":
    pytest.main([__file__])
