# ********RoostGPT********

# Test generated by RoostGPT for test py-api-aviation using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-3-5-sonnet-20240620-v1:0
# 
# Test file generated for /api/data/pirep_get for http method type GET 
# RoostTestHash=2fa6914fd1
# 
# 

# ********RoostGPT********
import pytest
import json
import os
from validator import SwaggerSchemaValidator

# Load test data
with open(os.path.join(os.path.dirname(__file__), 'api_data_pirep.json'), 'r') as f:
    test_data = json.load(f)

# Initialize SwaggerSchemaValidator
validator = SwaggerSchemaValidator('https://aviationweather.gov/data/schema/openapi.yaml')

@pytest.mark.parametrize("data", test_data)
def test_pirep_endpoint(api_client, config, data):
    endpoint = '/api/data/pirep'
    
    # Prepare request parameters
    params = {
        'id': data['id'],
        'distance': data['distance'],
        'bbox': ','.join(map(str, data['bbox'])),
        'format': data['format'],
        'age': data['age'],
        'level': data['level'],
        'inten': data['inten'],
        'date': data['date']
    }
    
    # Validate request parameters
    try:
        validator.validate_with_schema(params, {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "distance": {"type": "number"},
                "bbox": {"type": "string"},
                "format": {"type": "string", "enum": ["raw", "decoded", "json", "geojson", "xml"]},
                "age": {"type": "number"},
                "level": {"type": "string"},
                "inten": {"type": "string", "enum": ["lgt", "mod", "sev"]},
                "date": {"type": "string"}
            }
        })
    except Exception as e:
        pytest.fail(f"Request validation failed: {str(e)}")

    # Make API request
    response = api_client.get(endpoint, params=params)

    # Assert status code
    assert response.status_code == data['statusCode'], f"Expected status code {data['statusCode']}, but got {response.status_code}"

    # Validate response
    if response.status_code == 200:
        if data['format'] == 'json':
            try:
                validator.validate_json(response.json(), 'PirepResponse')
            except Exception as e:
                pytest.fail(f"Response validation failed: {str(e)}")
        elif data['format'] == 'geojson':
            try:
                validator.validate_json(response.json(), 'PirepGeoJsonResponse')
            except Exception as e:
                pytest.fail(f"Response validation failed: {str(e)}")
        elif data['format'] == 'xml':
            # XML validation is not implemented in the provided validator
            pass
        else:
            # For 'raw' and 'decoded' formats, just check if the response is a non-empty string
            assert isinstance(response.text, str) and response.text.strip(), "Expected non-empty string response"
    elif response.status_code == 400:
        try:
            validator.validate_json(response.json(), 'ErrorResponse')
        except Exception as e:
            pytest.fail(f"Error response validation failed: {str(e)}")

    # Additional assertions based on the scenario
    if data['scenario'] == 'successful operation':
        assert response.status_code == 200, f"Expected successful operation, but got status code {response.status_code}"
    elif data['scenario'] == 'Input validation errors':
        assert response.status_code == 400, f"Expected input validation error, but got status code {response.status_code}"

def test_invalid_format(api_client, config):
    endpoint = '/api/data/pirep'
    params = {
        'id': 'KMCO',
        'format': 'invalid_format'
    }
    response = api_client.get(endpoint, params=params)
    assert response.status_code == 400, f"Expected status code 400, but got {response.status_code}"

def test_missing_required_params(api_client, config):
    endpoint = '/api/data/pirep'
    response = api_client.get(endpoint)
    assert response.status_code == 400, f"Expected status code 400, but got {response.status_code}"

def test_invalid_bbox(api_client, config):
    endpoint = '/api/data/pirep'
    params = {
        'bbox': '200,-100,300,100'  # Invalid longitude/latitude values
    }
    response = api_client.get(endpoint, params=params)
    assert response.status_code == 400, f"Expected status code 400, but got {response.status_code}"

def test_invalid_date(api_client, config):
    endpoint = '/api/data/pirep'
    params = {
        'id': 'KMCO',
        'date': 'invalid_date'
    }
    response = api_client.get(endpoint, params=params)
    assert response.status_code == 400, f"Expected status code 400, but got {response.status_code}"

if __name__ == "__main__":
    pytest.main([__file__])
