# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=100d61e03c
# 
# 

# ********RoostGPT********
@ignore
Feature: /2.1/laureate/{laureateID} endpoint

Background:
  * url '{{ $processEnvironment.API_HOST }}'
  * def laureateID = 1

Scenario: Get laureate by ID - Success
  Given path '/2.1/laureate/' + laureateID
  When method GET
  Then status 200
  And match responseHeaders == {}

Scenario: Get laureate by ID - Invalid ID format
  Given path '/2.1/laureate/invalid'
  When method GET
  Then status 400
  And match responseHeaders == {}
  And match response == 
  """
  {
    "code": "#string",
    "message": "#string"
  }
  """ 

Scenario: Get laureate by ID - Laureate not found
  Given path '/2.1/laureate/9999'
  When method GET 
  Then status 404
  And match responseHeaders == {}
  And match response ==
  """
  {
    "code": "#string",
    "message": "#string"  
  }
  """

Scenario: Get laureate by ID - Invalid ID value
  Given path '/2.1/laureate/0'
  When method GET
  Then status 422 
  And match responseHeaders == {}
  And match response ==
  """
  {
    "code": "#string",
    "message": "#string"
  }  
  """
