# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roost-gpt4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=100d61e03c
# 
# 

# ********RoostGPT********
Feature: Validate API behavior with valid input payloads

Background:
* url target = karate.properties['API_HOST']
* def authHeader = karate.properties['AUTH_TOKEN']
* configure headers = { Authorization: '#(authHeader)' }

Scenario: Validate laureate API
* table payload = read('laureate_laureateID_get_karate.csv')  

Given path '/2.1/laureate/{laureateID}'    
And header Content-Type = 'application/json'
And request payload

# The API is called with the GET request
When method get

# The response status code should be 200
Then status 200

* def responseHeaders = responseHeaders
* match responseHeaders contains { 'Content-Type': '#string' }

* def actual = response

* match actual == { 'id': '#string','name': '#string'}

# The response should have minimum 1 record
And match each response[*].id exists
And match each response[*].name exists

# Asserting each required property in the response body against schema 
And match actual.name == '#string'
And match actual.id == '#string'
