# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roost-gpt4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=41cb7e02aa
# 
# 

# ********RoostGPT********
@debug
Feature: Laureates API endpoints testing

# Set the environment variable before running the test
Background:
 * url target: '{{ $processEnvironment.API_HOST }}'
 * header Authorization = '{{ $processEnvironment.AUTH_TOKEN }}'
 
# Initialize Data
 * csv payload = read('laureates_get_karate.csv')
 
Scenario Outline:

# Send a GET request
Given path '/2.1/laureates'
And param offset = '<offset>'
And param limit = '<limit>'
And param sort = '<sort>'
And param ID = '<ID>'
And param name = '<name>'
And param gender = '<gender>'
And param motivation = '<motivation>'
And param affiliation = '<affiliation>'
And param residence = '<residence>'
And param birthDate = '<birthDate>'
And param birthDateTo = '<birthDateTo>'
And param deathDate = '<deathDate>'
And param deathDateTo = '<deathDateTo>'
And param foundedDate = '<foundedDate>'
And param birthCity = '<birthCity>'
And param birthCountry = '<birthCountry>'
And param birthContinent = '<birthContinent>'
And param deathCity = '<deathCity>'
And param deathCountry = '<deathCountry>'
And param deathContinent = '<deathContinent>'
And param foundedCity = '<foundedCity>'
And param foundedCountry = '<foundedCountry>'
And param foundedContinent = '<foundedContinent>'
And param HeadquartersCity = '<HeadquartersCity>'
And param HeadquartersCountry = '<HeadquartersCountry>'
And param HeadquartersContinent = '<HeadquartersContinent>'
And param nobelPrizeYear = '<nobelPrizeYear>'
And param yearTo = '<yearTo>'
And param nobelPrizeCategory = '<nobelPrizeCategory>'
And param format = '<format>'
And param csvLang = '<csvLang>'
    
# Send request with parameters
When method get

# Validation
Then status 200
And match each response.laureates contains {"id": '#number'}
And match response.meta contains {"offset": '#number', "limit": '#number'}
And match header Content-Type contains 'application/json'

# Payload
Examples:
| payload |

