# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roost-gpt4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=41cb7e02aa
# 
# 

# ********RoostGPT********
Feature: Validate Laureates API

Background:
  * url '{{ $processEnvironment.API_HOST }}'

Scenario: Verify that GET /2.1/laureates returns 200 and contains expected fields
  Given path '/2.1/laureates'
  And param offset = 'value_from_csv' 
  And param limit = 'value_from_csv' 
  # Add the rest of the request parameters from CSV file
  When method get 
  Then status 200
  And match response.laureates contains {id:'#integer'}
  And match response.meta contains {offset:'#integer'}
  # Add the rest of the response fields checks according to API SPECIFICATION

Scenario: Verify that GET /2.1/laureates returns 400 when incorrect parameters are passed
  Given path '/2.1/laureates'
  And param offset = 'incorrect_value' 
  # Add more similar requests for other parameters
  When method get
  Then status 400
  
Scenario: Verify that GET /2.1/laureates returns 404 when resource not found
  Given path '/2.1/laureates'
  And param id = 'nonexistent_id' 
  # Add more similar requests for other parameters
  When method get
  Then status 404

Scenario: Verify that GET /2.1/laureates returns 422 when invalid parameters are passed
  Given path '/2.1/laureates'
  And param offset = 'invalid_value' 
  # Add more similar requests for other parameters
  When method get
  Then status 422
