# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roost-gpt4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=100d61e03c
# 
# 

# ********RoostGPT********
Feature: Testing the laureate API

Background:
* url target: '{{ $processEnvironment.API_HOST }}'

Scenario: Test GET laureate API with Valid laureateID
* def csvData = read('laureate_laureateID_get.csv')
* table laureateDetails
| laureateID |
| '#(csvData.laureateID)' |
* path '/2.1/laureate/{laureateID}', laureateDetails.laureateID
* method get
* status 200

Scenario: Test GET laureate API with Invalid laureateID
* def invalidLaureateID = 'invalidID'
* path '/2.1/laureate/{laureateID}', invalidLaureateID
* method get
* status 400

Scenario: Test GET laureate API with laureateID not found
* def nonExistentLaureateID = '9999999999'
* path '/2.1/laureate/{laureateID}', nonExistentLaureateID
* method get
* status 404

Scenario: Test GET laureate API with unspecified laureateID
* path '/2.1/laureate/{laureateID}', ''
* method get
* status 422
