# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API

Background:
    * url target
    * configure headers = read('classpath:headers.js')

Scenario: Get all Nobel Prizes
    Given path '/2.1/nobelPrizes'
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response.nobelPrizes == '#[]'
    And match each response.nobelPrizes contains {awardYear: '#number', category: '#object', categoryFullName: '#object', dateAwarded: '#string', prizeAmount: '#number', prizeAmountAdjusted: '#number', topMotivation: '#object', laureates: '#[]'}
    And match response.meta == '#object'
    And match response.links == '#[]'

Scenario: Get Nobel Prizes with pagination
    Given path '/2.1/nobelPrizes'
    And param offset = 10
    And param limit = 5  
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response.nobelPrizes == '#[5]'
    And match response.meta.offset == 10
    And match response.meta.limit == 5

Scenario: Get Nobel Prizes by year
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeYear = 2020
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match each response.nobelPrizes contains {awardYear: 2020}

Scenario: Get Nobel Prizes by year range
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeYear = 2015
    And param yearTo = 2020
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match each response.nobelPrizes contains {awardYear: '#? _ >= 2015 && _ <= 2020'}

Scenario: Get Nobel Prizes by category
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeCategory = 'phy'
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match each response.nobelPrizes contains {category: {en: 'Physics'}}
    
Scenario: Get Nobel Prizes with invalid year
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeYear = 1800
    When method GET
    Then status 400
    And match response == {code: '400', message: '#string'}

Scenario: Get Nobel Prizes with invalid category  
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeCategory = 'invalid'
    When method GET
    Then status 404
    And match response == {code: '404', message: '#string'}
