# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
  * url target
  * def auth_token = karate.get('AUTH_TOKEN')

Scenario Outline: Get Nobel Prize information for a specific category and year
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = auth_token
  When method GET
  Then status 200
  And match response.nobelPrize.awardYear == <year>
  And match response.nobelPrize.category.en == <categoryEn>
  And match response.nobelPrize.categoryFullName.en == <categoryFullNameEn>
  And match response.nobelPrize.dateAwarded == <dateAwarded>
  And match response.nobelPrize.prizeAmount == <prizeAmount>
  And match response.nobelPrize.prizeAmountAdjusted == <prizeAmountAdjusted>
  And match response.nobelPrize.topMotivation.en == <topMotivationEn>
  And match each response.nobelPrize.laureates == 
    """
    {
      id: '#number',
      name: {
        en: '#string',
        se: '##string',
        false: '##string'
      },
      portion: '#string',
      sortOrder: '#string',
      motivation: {
        en: '#string',
        se: '##string',
        false: '##string'  
      },
      links: '#array'
    }
    """

  Examples:
    | category | year | categoryEn | categoryFullNameEn   | dateAwarded | prizeAmount | prizeAmountAdjusted | topMotivationEn                       |  
    | phy      | 2020 | Physics    | Nobel Prize in Physics | 2020-12-10  | 10000000    | 10500000            | "for the discovery that black hole formation is a robust prediction of the general theory of relativity" |
    | che      | 2019 | Chemistry  | Nobel Prize in Chemistry | 2019-12-10 | 9000000    | 9500000             | "for the development of lithium-ion batteries" |


Scenario: Get Nobel Prize with invalid category
  Given path '/2.1/nobelPrize/invalidcategory/2020'
  And header Authorization = auth_token  
  When method GET
  Then status 400
  And match response == 
    """
    {
      code: '#string',
      message: '#string'
    }
    """ 

Scenario: Get Nobel Prize for a future year
  Given path '/2.1/nobelPrize/phy/2050'
  And header Authorization = auth_token
  When method GET 
  Then status 404
  And match response ==
    """
    {
      code: '#string',
      message: '#string'  
    }
    """
