# ********RoostGPT********

# Test generated by RoostGPT for test karate using AI Type Azure Open AI and AI Model roost-gpt4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API Tests

  Background:
    * url target: '{{ $processEnvironment.API_HOST }}'
    * header Authorization = '{{ $processEnvironment.AUTH_TOKEN }}'
    * def nobelPrize_category_year_get = read('nobelPrize_category_year_get.csv')
    
  Scenario Outline: Verify nobelPrize information by category and year
    Given path '2.1', 'nobelPrize', '<category>', '<year>'
    When method get
    Then status 200
    And match response contains {"nobelPrize": "#notnull"}
    And match response.nobelPrize.awardYear == '<year>'
    And match response.nobelPrize.category.* == '<category>'
    And match response.nobelPrize.categoryFullName.* == '#notnull'
    And match response.nobelPrize.dateAwarded == '#string'
    And match response.nobelPrize.prizeAmount == '#integer'
    And match response.nobelPrize.prizeAmountAdjusted == '#integer'
    And match response.nobelPrize.topMotivation.* == '#notnull'
    And match each response.nobelPrize.laureates contains {"id": '#notnull',"name": '#notnull',"portion": '#notnull',"sortOrder": '#notnull',"motivation": '#notnull',"links": '#array'}
    
    Examples:
    | nobelPrize_category_year_get |

  @error
  Scenario Outline: Verify error responses
    Given path '2.1', 'nobelPrize', '<category>', '<year>'
    When method get
    Then status <errorStatus>
    And match response == {code: '#string', message: '#string'}
  
    Examples:
      | category | year  | errorStatus |
      | 'test' | '1234' | 400 |
      | 'test' | '2020' | 404 |
      | 'test' | 'abcd' | 422 |
