# ********RoostGPT********

# Test generated by RoostGPT for test claude-karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=00eb351b13
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.get('authToken', '{{$processEnvironment.AUTH_TOKEN}}')

Scenario Outline: Get Nobel Prize by category and year
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match header Content-Type contains 'application/json'
  And match response.nobelPrize.awardYear == <year>
  And match response.nobelPrize.category.en == '<categoryEn>'
  And match response.nobelPrize.categoryFullName.en == '<categoryFullEn>'
  And match response.nobelPrize.dateAwarded == '#? _ =~ /\\d{4}-\\d{2}-\\d{2}/'
  And match response.nobelPrize.prizeAmount == '#number'
  And match response.nobelPrize.prizeAmountAdjusted == '#number'
  And match response.nobelPrize.topMotivation.en == '#string'
  And match each response.nobelPrize.laureates == 
    """
    {
      id: '#number',
      name: {
        en: '#string',
        se: '##string',
        no: '##string'        
      },
      portion: '#? _ == "1" || _ == "1/2" || _ == "1/3" || _ == "1/4"',
      sortOrder: '#? _ == "1" || _ == "2" || _ == "3"',
      motivation: {
        en: '#string',
        se: '##string',
        no: '##string'
      },
      links: '#[] link'
    }
    """
  And def link =
    """
    {
      rel: '#string',
      href: '#string',
      action: '#string',
      types: '#string'
    }
    """
    
  Examples:
    | category | year | categoryEn | categoryFullEn |
    | che      | 1989 | Chemistry  | Chemistry      |
    | eco      | 1969 | Economics  | Economic Sciences |
    | lit      | 1947 | Literature | Literature     |
    | pea      | 1962 | Peace      | Peace          |
    | phy      | 1921 | Physics    | Physics        |
    | med      | 1972 | Medicine   | Physiology or Medicine |

Scenario Outline: Get Nobel Prize with invalid category or year
  Given path '/2.1/nobelPrize/<category>/<year>'
  And header Authorization = authToken  
  When method GET
  Then status <status>
  And match header Content-Type contains 'application/json'
  And match response == 
    """
    {
      code: '#string',
      message: '#string'
    }
    """

  Examples:
    | category | year | status |
    | invalid  | 1901 | 400    |
    | eco      | 1800 | 400    |
    | med      | 2100 | 404    |
